In [27]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [28]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [29]:
df.shape

(569, 33)

In [30]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [31]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [33]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [34]:
X_train

array([[-1.01085425,  0.13583029, -1.01429778, ..., -0.70629186,
        -0.00918268, -0.32889774],
       [ 0.46747427, -0.32466928,  0.47716132, ...,  1.01255481,
         1.4860583 ,  1.1945995 ],
       [-0.79328892,  0.12881761, -0.82907862, ..., -1.29678618,
        -0.54542972, -0.40418036],
       ...,
       [ 0.27780193,  0.64074353,  0.22076624, ...,  0.58904454,
        -0.35132803, -0.25919161],
       [-0.32189738, -0.76179324, -0.35025878, ..., -0.12789784,
         0.80834731,  0.69494594],
       [-0.2521649 , -0.4321971 , -0.31022232, ..., -0.97340584,
        -0.19999451, -0.63560473]])

In [35]:
y_train

245    B
11     M
522    B
261    M
17     M
      ..
22     M
87     M
54     M
292    B
246    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [36]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [37]:
y_train

array([0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,

# Convet the Numpy arrays to PyTorch tensors


In [38]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [39]:
X_train_tensor.shape

torch.Size([455, 30])

In [40]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

Gradients tell us how much and in which direction a model’s output (or loss) changes when we slightly change a parameter (like weights).  

   """requires_grad=True  
    tells PyTorch to track gradients  
    Needed for backpropagation  
    Allows .backward() to compute gradients for this tensor"""

In [41]:
class SimpleNeuralNetworct():

  def __init__(self, X): #constructor , X is a training set

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True) #initialize weights randomly

    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X): # (w*X+b) *sigmoid
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


### Important Parameters

In [42]:
learning_rate = 0.1
epochs = 30

### Training Pipeline

In [43]:
# create model
model = SimpleNeuralNetworct(X_train_tensor) #input data

# define loop
for epoch in range(epochs):
   #Four steps for traing the model
  # 1 forward pass (z=w*X+b)
  y_pred = model.forward(X_train_tensor)

  # 2 loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # 3 backward pass
  loss.backward()

  # 4 parameters update
  with torch.no_grad(): #Gradient tracking off
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 4.213606524254501
Epoch: 2, Loss: 4.122016297534045
Epoch: 3, Loss: 4.026378974066543
Epoch: 4, Loss: 3.9245350635186504
Epoch: 5, Loss: 3.8144919639511334
Epoch: 6, Loss: 3.7018727699760974
Epoch: 7, Loss: 3.5889791849261354
Epoch: 8, Loss: 3.469286148413016
Epoch: 9, Loss: 3.346640786755466
Epoch: 10, Loss: 3.219432515756681
Epoch: 11, Loss: 3.0899812735610186
Epoch: 12, Loss: 2.961375332390924
Epoch: 13, Loss: 2.826878026283293
Epoch: 14, Loss: 2.682849422017343
Epoch: 15, Loss: 2.542300370036792
Epoch: 16, Loss: 2.402454887921317
Epoch: 17, Loss: 2.26402888778403
Epoch: 18, Loss: 2.1287386770770667
Epoch: 19, Loss: 1.9971043909991393
Epoch: 20, Loss: 1.8644160603110096
Epoch: 21, Loss: 1.7336155233631327
Epoch: 22, Loss: 1.608252132984167
Epoch: 23, Loss: 1.4932332826791745
Epoch: 24, Loss: 1.3857612318900423
Epoch: 25, Loss: 1.2906944616919371
Epoch: 26, Loss: 1.2082884531532956
Epoch: 27, Loss: 1.1381325280049617
Epoch: 28, Loss: 1.0791227447469407
Epoch: 29, Loss

In [46]:
model.bias

tensor([-0.1303], dtype=torch.float64, requires_grad=True)

### Evaluation

In [45]:
# model evaluation
with torch.no_grad(): #At the evalution time no need of backpropagation so we off the graded tracking
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float() # if y_pres >0.5 then 1 other 0
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

  print(y_pred)
  print(y_test_tensor)


Accuracy: 0.5277008414268494
tensor([[0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
     